# Generated by Django 4.2.2 on 2023-07-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField()),
                ('image', models.ImageField(max_length=500, upload_to='books')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
